import request from '../utils/request';

const ackbarUrl = process.env.ACKBAR_URL;
const requestAckbar = (path, method, payload) => {
  const fetchOptions = {
    method,
    headers: new Headers({
      'Content-Type': 'application/json',
      Authorization: `Bearer ${(payload && payload.token) || ''}`,
    }),
  };

  if (method === 'GET') {
    return request(`${ackbarUrl}/${path}`, fetchOptions);
  }
  return request(`${ackbarUrl}/${path}`, {
    ...fetchOptions,
    body: JSON.stringify(payload || {}),
  });
};

export const getGameList = () =>
  Promise.resolve([
    {
      id: 1,
      name: 'Tokaido',
      year: '2012',
      age: '8+',
      numberOfPlayers: '2-5',
      duration: '45',
      description:
        'In Tokaido, each player is a traveler crossing the "East sea road", one of the most magnificent roads of Japan. While traveling, you will meet people, taste fine meals, collect beautiful items, discover great panoramas, and visit temples and wild places but at the end of the day, when everyone has arrived at the end of the road you\'ll have to be the most initiated traveler – which means that you\'ll have to be the one who discovered the most interesting and varied things.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703532/Tokaido.jpg',
      genre: 'Viagem',
      publisher: 'Galápagos Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 2,
      name: '7 Wonders',
      year: '2010',
      age: '10+',
      numberOfPlayers: '2-7',
      duration: '30',
      description:
        'You are the leader of one of the 7 great cities of the Ancient World. Gather resources, develop commercial routes, and affirm your military supremacy. Build your city and erect an architectural wonder which will transcend future times.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703529/7wonders.jpg',
      genre: 'Civilização',
      publisher: 'Galápagos Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 3,
      name: 'Takenoko',
      year: '2011',
      age: '8+',
      numberOfPlayers: '2-4',
      duration: '45',
      description:
        'A long time ago at the Japanese Imperial court, the Chinese Emperor offered a giant panda bear as a symbol of peace to the Japanese Emperor. Since then, the Japanese Emperor has entrusted his court members (the players) with the difficult task of caring for the animal by tending to his bamboo garden.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703524/Takenoko.jpg',
      genre: 'Agricultura',
      publisher: 'Galápagos Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 4,
      name: 'Zombicide',
      year: '2012',
      age: '13+',
      numberOfPlayers: '1-6',
      duration: '90',
      description:
        'Zombicide is a collaborative game in which players take the role of a survivor – each with unique abilities – and harness both their skills and the power of teamwork against the hordes of unthinking undead! Zombies are predictable, stupid but deadly, controlled by simple rules and a deck of cards. Unfortunately for you, there are a LOT more zombies than you have bullets.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703537/Zombicide.jpg',
      genre: 'Zumbis',
      publisher: 'Galápagos Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 5,
      name: 'A Guerra dos Tronos: Board Game',
      year: '2014',
      age: '14+',
      numberOfPlayers: '3 a 6',
      duration: '135',
      description:
        'King Robert Baratheon is dead, and the lands of Westeros brace for battle.  In the second edition of A Game of Thrones: The Board Game, three to six players take on the roles of the great Houses of the Seven Kingdoms of Westeros, as they vie for control of the Iron Throne through the use of diplomacy and warfare. Based on the best-selling A Song of Ice and Fire series of fantasy novels by George R.R. Martin, A Game of Thrones is an epic board game in which it will take more than military might to win. Will you take power through force, use honeyed words to coerce your way onto the throne, or rally the townsfolk to your side? Through strategic planning, masterful diplomacy, and clever card play, spread your influence over Westeros!',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703530/A_Guerra_dos_Tronos.png',
      genre: 'Guerra',
      publisher: 'Galápagos Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 6,
      name: 'Abalone',
      year: '1987',
      age: '7+',
      numberOfPlayers: '2',
      duration: '30',
      description:
        "This beautiful and functional board has room for two teams of large marbles. Players take turns pushing the marbles around the board, with the goal of pushing six of the opposing player's marbles off the board. The central idea is that a column of marbles has weight given by the number of marbles in line. Someone will need to push with a heavier group of marbles in order to push the column along that axis. However, with six possible directions, it's difficult to defend yourself perfectly. Also, it's possible to play the game with up to six players when supplemental marble sets are purchased.",
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703535/Abalone.jpg',
      genre: 'Estratégia',
      publisher: 'Mitra',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 7,
      name: 'Agricola',
      year: '2015',
      age: '12+',
      numberOfPlayers: '1 a 5',
      duration: '120',
      description:
        "In Agricola, you're a farmer in a wooden shack with your spouse and little else. On a turn, you get to take only two actions, one for you and one for the spouse, from all the possibilities you'll find on a farm: collecting clay, wood, or stone; building fences; and so on. You might think about having kids in order to get more work accomplished, but first you need to expand your house. And what are you going to feed all the little rugrats?",
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703534/Agricola.jpg',
      genre: 'Agricultura',
      publisher: 'Devir Brasil',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 8,
      name: 'Alhambra',
      year: '2017',
      age: '8+',
      numberOfPlayers: '2 a 6',
      duration: '60',
      description:
        'Granada, 1278. At the foot of the Sierra Nevada mountains, one of the most exciting and interesting project of the Spanish Middle Ages begins: the construction of the ALHAMBRA.  The best master builders in the whole of Europe and Arabia want to demonstrate their skill. Employ the most suitable teams of builders and make sure that you always have enough of the right currency. Because no matter whether they are stonemasons from the north or horticulturalists from the south, they all want a proper wage and insist on their "native" currency. With their help towers can be constructed, gardens laid out, pavilions and arcades erected and seraglios and chambers built.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703536/Alhambra.jpg',
      genre: 'Civilização',
      publisher: 'Flick Game Studio',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 9,
      name: 'Arcadia Quest',
      year: '2016',
      age: '13+',
      numberOfPlayers: '2 a 4',
      duration: '60',
      description:
        'In Arcadia Quest, players lead guilds of intrepid heroes on an epic campaign to dethrone the vampire lord and reclaim the mighty Arcadia for their own. But only one guild may lead in the end, so players must battle against each other as well as against the monstrous occupying forces.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703525/Arcadia_Quest.jpg',
      genre: 'Aventura',
      publisher: 'Galápagos Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 10,
      name: 'Azul',
      year: '2018',
      age: '8+',
      numberOfPlayers: '2 a 4',
      duration: '30',
      description:
        'Introduced by the Moors, azulejos (originally white and blue ceramic tiles) were fully embraced by the Portuguese when their king Manuel I, on a visit to the Alhambra palace in Southern Spain, was mesmerized by the stunning beauty of the Moorish decorative tiles. The king, awestruck by the interior beauty of the Alhambra, immediately ordered that his own palace in Portugal be decorated with similar wall tiles. As a tile-laying artist, you have been challenged to embellish the walls of the Royal Palace of Evora.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703527/Azul.jpg',
      genre: 'Estratégia',
      publisher: 'Galápagos Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 11,
      name: 'Black Stories',
      year: '2014',
      age: '12+',
      numberOfPlayers: '2 a 15',
      duration: '20',
      description:
        '50 black stories, 31 crimes, 49 corpses, 11 murders, 12 suicides and one deadly meal. How could that have happened? Black Stories are fiddly, morbid and mysterious riddles for teenagers and adults. The players try to reconstruct the crime by asking, guessing and fiddling about. A spooky card game just right for any party.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703537/Black_Stories.jpg',
      genre: 'Party Game',
      publisher: 'Galápagos Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 12,
      name: ' Carcassonne',
      year: '2002',
      age: '8+',
      numberOfPlayers: '2 a 5',
      duration: '45',
      description:
        'Carcassonne is a tile-placement game in which the players draw and place a tile with a piece of southern French landscape on it. The tile might feature a city, a road, a cloister, grassland or some combination thereof, and it must be placed adjacent to tiles that have already been played, in such a way that cities are connected to cities, roads to roads, etcetera. Having placed a tile, the player can then decide to place one of his meeples on one of the areas on it: on the city as a knight, on the road as a robber, on a cloister as a monk, or on the grass as a farmer. When that area is complete, that meeple scores points for its owner.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703539/Carcassonne.jpg',
      genre: 'Civilização',
      publisher: 'Devir Brasil',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 13,
      name: 'Cartas de Whitechapel',
      year: '2018',
      age: '13+',
      numberOfPlayers: '2 a 6',
      duration: '120',
      description:
        'Get ready to enter the poor and dreary Whitechapel district in London 1888 – the scene of the mysterious Jack the Ripper murders – with its crowded and smelly alleys, hawkers, shouting merchants, dirty children covered in rags who run through the crowd and beg for money, and prostitutes – called "the wretched" – on every street corner.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703533/Cartas_de_Whitechapel.jpg',
      genre: 'Dedução',
      publisher: 'Redbox Editora',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 14,
      name: 'Citadels',
      year: '2013',
      age: '10+',
      numberOfPlayers: '2 a 8',
      duration: '90',
      description:
        'In Citadels, players take on new roles each round to represent characters they hire in order to help them acquire gold and erect buildings. The game ends at the close of a round in which a player erects his/her eighth building. Players then tally their points, and the player with the highest score wins.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703534/Citadels.jpg',
      genre: 'Civilização',
      publisher: 'Galápagos Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 15,
      name: 'Codenames',
      year: '2016',
      age: '14+',
      numberOfPlayers: '2 a 8',
      duration: '15',
      description:
        'Two rival spymasters know the secret identities of 25 agents. Their teammates know the agents only by their CODENAMES.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703538/Codename.jpg',
      genre: 'Party Game',
      publisher: 'Devir Brasil',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 16,
      name: 'CV',
      year: '2016',
      age: '10+',
      numberOfPlayers: '2 a 4',
      duration: '60',
      description:
        'Have you ever wondered who you would have been if your life had gone differently? How would you direct your life if everything were up to you? Maybe you would be a magician, or travel around the world? Or maybe big business tempts you, and your goal would be to earn a million dollars?',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703533/CV.jpg',
      genre: 'Engraçado',
      publisher: 'Conclave Editora',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 17,
      name: 'Dead of Winter: A Noite Sem Fim',
      year: '2016',
      age: '13+',
      numberOfPlayers: '2 a 5',
      duration: '120',
      description:
        'Dead of Winter: A Crossroads Game, the first game in this series, puts 2-5 players in a small, weakened colony of survivors in a world where most of humanity is either dead or diseased, flesh-craving monsters. Each player leads a faction of survivors with dozens of different characters in the game.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703523/Dead_of_Winter_A_Noite_Sem_Fim.jpg',
      genre: 'Zumbis',
      publisher: 'Galápagos Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 18,
      name: 'Dixit',
      year: '2008',
      age: '8+',
      numberOfPlayers: '3 a 6',
      duration: '30',
      description:
        'One player is the storyteller for the turn and looks at the images on the 6 cards in her hand. From one of these, she makes up a sentence and says it out loud (without showing the card to the other players).  Each other player selects the card in their hands which best matches the sentence and gives the selected card to the storyteller, without showing it to the others.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703528/Dixit.jpg',
      genre: 'Party Game',
      publisher: 'Galápagos Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 19,
      name: 'Dominion',
      year: '2015',
      age: '8+',
      numberOfPlayers: '2 a 4',
      duration: '30',
      description:
        'You are a monarch, like your parents before you, a ruler of a small pleasant kingdom of rivers and evergreens. Unlike your parents, however, you have hopes and dreams! You want a bigger and more pleasant kingdom, with more rivers and a wider variety of trees. You want a Dominion! In all directions lie fiefs, freeholds, and feodums. All are small bits of land, controlled by petty lords and verging on anarchy. You will bring civilization to these people, uniting them under your banner.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703534/Dominion.jpg',
      genre: 'Medieval',
      publisher: 'Conclave Editora',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 20,
      name: 'EcoFluxx',
      year: '2005',
      age: '8+',
      numberOfPlayers: '2 a 6',
      duration: '15',
      description:
        'What\'s in EcoFluxx? Well, it has a whole food chain of woodland creatures from leaves to bears. It has frogs and snakes and trees and fish and spiders and rabbits and mice and mushrooms and worms. It has air and water and dirt, and it has the humans whose pollution can endanger such things. It has all the standard new rules and actions that make it Fluxx, plus a few new ones that go with the theme, including the Composting rule (which lets you draw from the bottom of the discard pile) and new types of "eating" goals (which let you win the game if your Keeper says it eats one of the other Keepers in play).',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703525/EcoFluxx.jpg',
      genre: 'Cartas',
      publisher: 'Copag',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 21,
      name: 'Eldritch Horror',
      year: '2014',
      age: '14+',
      numberOfPlayers: '1 a 8',
      duration: '240',
      description:
        'Across the globe, ancient evil is stirring. Now, you and your trusted circle of colleagues must travel around the world, working against all odds to hold back the approaching horror. Foul monsters, brutal encounters, and obscure mysteries will take you to your limit and beyond. All the while, you and your fellow investigators must unravel the otherworldy mysteries scattered around the globe in order to push back the gathering mayhem that threatens to overwhelm humanity. The end draws near! Do you have the courage to prevent global destruction?',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703525/Eldritch_Horror.png',
      genre: 'Aventura',
      publisher: 'Galápagos Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 22,
      name: 'Flash Point: Ao Resgate',
      year: '2015',
      age: '10+',
      numberOfPlayers: '1 a 6',
      duration: '45',
      description:
        'The call comes in... "911, what is your emergency?" On the other end is a panicked response of "FIRE!" Moments later you don the protective suits that will keep you alive, gather your equipment and rush to the scene of a blazing inferno. The team has only seconds to assess the situation and devise a plan of attack – then you spring into action like the trained professionals that you are. You must face your fears, never give up, and above all else work as a team because the fire is raging, the building is threatening to collapse, and lives are in danger.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703529/Flash_Point.jpg',
      genre: 'Aventura',
      publisher: 'Mandala Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 23,
      name: 'For Sale',
      year: '2014',
      age: '8+',
      numberOfPlayers: '3 a 6',
      duration: '20',
      description:
        "For Sale is a quick, fun game nominally about buying and selling real estate. During the game's two distinct phases, players first bid for several buildings then, after all buildings have been bought, sell the buildings for the greatest profit possible.",
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703527/for-sale.jpg',
      genre: 'Cartas',
      publisher: 'Meeple Virus',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 24,
      name: 'Great Western Trail',
      year: '2017',
      age: '12+',
      numberOfPlayers: '2 a 4',
      duration: '150',
      description:
        'America in the 19th century: You are a rancher and repeatedly herd your cattle from Texas to Kansas City, where you send them off by train. This earns you money and victory points. Needless to say, each time you arrive in Kansas City, you want to have your most valuable cattle in tow. However, the "Great Western Trail" not only requires that you keep your herd in good shape, but also that you wisely use the various buildings along the trail. Also, it might be a good idea to hire capable staff: cowboys to improve your herd, craftsmen to build your very own buildings, or engineers for the important railroad line.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703530/Great_Western_Trail.jpg',
      genre: 'Oeste Americano',
      publisher: 'Conclave Editora',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 25,
      name: 'Hive',
      year: '2018',
      age: '9+',
      numberOfPlayers: '2',
      duration: '20',
      description:
        'Hive is a highly addictive strategic game for two players that is not restricted by a board and can be played anywhere on any flat surface. Hive is made up of twenty two pieces, eleven black and eleven white, resembling a variety of creatures each with a unique way of moving.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703526/Hive.jpg',
      genre: 'Estratégia',
      publisher: 'Redbox Editora',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 26,
      name: 'Ilha Proibida - Forbidden Island',
      year: '2014',
      age: '10+',
      numberOfPlayers: '2 a 4',
      duration: '30',
      description:
        "Forbidden Island is a visually stunning cooperative board game. Instead of winning by competing with other players like most games, everyone must work together to win the game. Players take turns moving their pawns around the 'island', which is built by arranging the many beautifully screen-printed tiles before play begins. As the game progresses, more and more island tiles sink, becoming unavailable, and the pace increases. Players use strategies to keep the island from sinking, while trying to collect treasures and items. As the water level rises, it gets more difficult- sacrifices must be made.",
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703537/a_ilha_proibida.jpg',
      genre: 'Aventura',
      publisher: 'Devir Brasil',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 27,
      name: 'King of Tokyo',
      year: '2014',
      age: '8+',
      numberOfPlayers: '2 a 6',
      duration: '30',
      description:
        'In King of Tokyo, you play mutant monsters, gigantic robots, and strange aliens—all of whom are destroying Tokyo and whacking each other in order to become the one and only King of Tokyo.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703528/King_of_Tokyo.jpg',
      genre: 'Sci-Fi',
      publisher: 'Galápagos Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 28,
      name: 'Kingdomino',
      year: '2017',
      age: '8+',
      numberOfPlayers: '2 a 4',
      duration: '15',
      description:
        'In Kingdomino, you are a Lord seeking new lands in which to expand your kingdom. You must explore all the lands, wheat fields, lakes, and mountains in order to spot the best plots. But be careful as some other Lords also covet these lands...',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703530/Kingdomino.png',
      genre: 'Civilização',
      publisher: 'PaperGames',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 29,
      name: 'Letters from Whitechapel',
      year: '2018',
      age: '13+',
      numberOfPlayers: '2 a 6',
      duration: '120',
      description:
        'Get ready to enter the poor and dreary Whitechapel district in London 1888 – the scene of the mysterious Jack the Ripper murders – with its crowded and smelly alleys, hawkers, shouting merchants, dirty children covered in rags who run through the crowd and beg for money, and prostitutes – called "the wretched" – on every street corner.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703533/Cartas_de_Whitechapel.jpg',
      genre: 'Dedução',
      publisher: 'Redbox Editora',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 30,
      name: 'Love Letter',
      year: '2014',
      age: '10+',
      numberOfPlayers: '2 a 4',
      duration: '20',
      description:
        'All of the eligible young men (and many of the not-so-young) seek to woo the princess of Tempest. Unfortunately, she has locked herself in the palace, and you must rely on others to take your romantic letters to her. Will yours reach her first?',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703533/Love_Letter.jpg',
      genre: 'Cartas ',
      publisher: 'Galápagos Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 31,
      name: 'Mansion of Madness',
      year: '2017',
      age: '14+',
      numberOfPlayers: '1 a 5',
      duration: '180',
      description:
        "Mansions of Madness: Second Edition is a fully cooperative, app-driven board game of horror and mystery for one to five players that takes place in the same universe as Eldritch Horror and Elder Sign. Let the immersive app guide you through the veiled streets of Innsmouth and the haunted corridors of Arkham's cursed mansions as you search for answers and respite. Eight brave investigators stand ready to confront four scenarios of fear and mystery, collecting weapons, tools, and information, solving complex puzzles, and fighting monsters, insanity, and death. Open the door and step inside these hair-raising Mansions of Madness: Second Edition. It will take more than just survival to conquer the evils terrorizing this town.",
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703545/Mansion_of_Madness.png',
      genre: 'Aventura',
      publisher: 'Galápagos Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 32,
      name: 'Monopoly',
      year: '1933',
      age: '8+',
      numberOfPlayers: '2 a  8',
      duration: '180',
      description:
        'Players take the part of land owners, attempting to buy and then develop their land. Income is gained by other players visiting their properties and money is spent when they visit properties belonging to other players. When times get tough, players may have to mortgage their properties to raise cash for fines, taxes and other misfortunes.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703531/Monopoly.jpg',
      genre: 'Negociação',
      publisher: 'Hasbro',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 33,
      name: 'Pandemic',
      year: '2015',
      age: '10+',
      numberOfPlayers: '2 a 4',
      duration: '60',
      description:
        'In Pandemic, several virulent diseases have broken out simultaneously all over the world! The players are disease-fighting specialists whose mission is to treat disease hotspots while researching cures for each of four plagues before they get out of hand.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703524/Pandemic.jpg',
      genre: 'Médico',
      publisher: 'Devir Brasil',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 34,
      name: 'Power Grid',
      year: '2016',
      age: '12+',
      numberOfPlayers: '2 a 6',
      duration: '120',
      description:
        'Power Grid is the updated release of the Friedemann Friese crayon game Funkenschlag. It removes the crayon aspect from network building in the original edition, while retaining the fluctuating commodities market like Crude: The Oil Game and an auction round intensity reminiscent of The Princes of Florence.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703530/Power_Grid.jpg',
      genre: 'Economia',
      publisher: 'Galápagos Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 35,
      name: 'Princess of Florence',
      year: '2000',
      age: '13+',
      numberOfPlayers: '2 a 5',
      duration: '90',
      description:
        'Players attract artists and scholars trying to become the most prestigious family in Florence. Each player is given a palace grid and reference chart and attempts to gain the most victory points after seven rounds. Scoring victory points can be done in a variety of ways although most will be earned by playing profession cards to generate work points. There are a variety of professions such as astronomers, organists and architects. Each is attracted to a particular combination of building, landscape feature, and social freedom',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703537/Princess_of_Florence.jpg',
      genre: 'Civilização',
      publisher: 'Rio Grande Games',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 36,
      name: 'Puerto Rico',
      year: '2015',
      age: '12+',
      numberOfPlayers: '2 a 5',
      duration: '90',
      description:
        'Players attract artists and scholars trying to become the most prestigious family in Florence. Each player is given a palace grid and reference chart and attempts to gain the most victory points after seven rounds. Scoring victory points can be done in a variety of ways although most will be earned by playing profession cards to generate work points. There are a variety of professions such as astronomers, organists and architects. Each is attracted to a particular combination of building, landscape feature, and social freedom. The more the player can match these preferences then the more work points are generated. If a player satisfies the minimum requirement of work points, which increases each round, then the work can be created and the player can then trade the work points for cash and/or victory points.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703523/Puerto_Rico.jpg',
      genre: 'Civilização',
      publisher: 'Grow ',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 37,
      name: 'Scythe',
      year: '2017',
      age: '14+',
      numberOfPlayers: '1 a 5',
      duration: '180',
      description:
        'It is a time of unrest in 1920s Europa. The ashes from the first great war still darken the snow. The capitalistic city-state known simply as “The Factory”, which fueled the war with heavily armored mechs, has closed its doors, drawing the attention of several nearby countries.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703541/Scythe.jpg',
      genre: 'Estratégia ',
      publisher: 'Ludofy Creative',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 38,
      name: 'Small World',
      year: '2015',
      age: '8+',
      numberOfPlayers: '2 a 5',
      duration: '80',
      description:
        'In Small World, players vie for conquest and control of a world that is simply too small to accommodate them all.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703529/Small_World.jpg',
      genre: 'Civilização ',
      publisher: 'Galápagos Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 39,
      name: 'Splendor',
      year: '2015',
      age: '10+',
      numberOfPlayers: '2 a 4',
      duration: '30',
      description:
        "Splendor is a game of chip-collecting and card development. Players are merchants of the Renaissance trying to buy gem mines, means of transportation, shops—all in order to acquire the most prestige points. If you're wealthy enough, you might even receive a visit from a noble at some point, which of course will further increase your prestige.",
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703526/Splendor.jpg',
      genre: 'Economia',
      publisher: 'Galápagos Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 40,
      name: 'Stone Age',
      year: '2015',
      age: '10+',
      numberOfPlayers: '2 a 4',
      duration: '60',
      description:
        'The "Stone Age" times were hard indeed. In their roles as hunters, collectors, farmers, and tool makers, our ancestors worked with their legs and backs straining against wooden plows in the stony earth. Of course, progress did not stop with the wooden plow. People always searched for better tools and more productive plants to make their work more effective.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703526/Stone_Age.jpg',
      genre: 'Civilização',
      publisher: 'Devir Brasil',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 41,
      name: 'Sushi Go!',
      year: '2016',
      age: '8+',
      numberOfPlayers: '2 a 5',
      duration: '15',
      description:
        "In the super-fast sushi card game Sushi Go!, you are eating at a sushi restaurant and trying to grab the best combination of sushi dishes as they whiz by. Score points for collecting the most sushi rolls or making a full set of sashimi. Dip your favorite nigiri in wasabi to triple its value! And once you've eaten it all, finish your meal with all the pudding you've got! But be careful which sushi you allow your friends to take; it might be just what they need to beat you!",
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703534/Sushi_Go.jpg',
      genre: 'Party Game',
      publisher: 'Devir Brasil',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 42,
      name: 'Tesouro Inca',
      year: '2015',
      age: '8+',
      numberOfPlayers: '3 a 8',
      duration: '20',
      description:
        'Diamant — also published as Incan Gold — is a quick, fun press-your-luck game. Players venture down mine shafts or explore paths in the jungle by turning up cards from a deck and evenly sharing the gems they find on the way, with any leftover gems being placed on the card. Before the next card is revealed, you have the chance to leave the mine and stash your holdings, including any gems you get on the way out.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703535/Tesouro_Inca.jpg',
      genre: 'Aventura',
      publisher: 'Grow ',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 43,
      name: 'The Manhattan Project',
      year: '2017',
      age: '13+',
      numberOfPlayers: '2 a 5',
      duration: '120',
      description:
        "The Manhattan Project makes you the leader of a great nation's atomic weapons program in a deadly race to build bigger and better bombs. You must assign your workers to multiple projects: building your bomb-making infrastructure, expending your military to protect it, or sending your spies to steal your rival's hard work!",
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703533/The_Manhattan_Project.png',
      genre: 'Estratégia ',
      publisher: 'Pensamento Coletivo',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 44,
      name: 'The Resistance',
      year: '2014',
      age: '13+',
      numberOfPlayers: '5 a 10',
      duration: '30',
      description:
        'The Empire must fall. Our mission must succeed. By destroying their key bases, we will shatter Imperial strength and liberate our people. Yet spies have infiltrated our ranks, ready for sabotage. We must unmask them. In five nights we reshape destiny or die trying. We are the Resistance!',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703531/The-Resistance.jpg',
      genre: 'Dedução ',
      publisher: 'Galápagos Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 45,
      name: 'The Settlers of Catan',
      year: '1995',
      age: '10+',
      numberOfPlayers: '3 a 6',
      duration: '90',
      description:
        'In Catan (formerly The Settlers of Catan), players try to be the dominant force on the island of Catan by building settlements, cities, and roads. On each turn dice are rolled to determine what resources the island produces. Players collect these resources (cards)—wood, grain, brick, sheep, or stone—to build up their civilizations to get to 10 victory points and win the game.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703536/The_Settlers_of_Catan.jpg',
      genre: 'Civilização ',
      publisher: 'Grow ',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 46,
      name: 'Through the Ages: Uma Nova história da Civilização',
      year: '2017',
      age: '14+',
      numberOfPlayers: '2 a 4',
      duration: '180',
      description:
        'Through the Ages is a civilization building game. Each player attempts to build the best civilization through careful resource management, discovering new technologies, electing the right leaders, building wonders and maintaining a strong military. Weakness in any area can be exploited by your opponents. The game takes place throughout the ages beginning in the age of antiquity and ending in the modern age.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703531/Through_the_AgesUma_Nova_hist%C3%B3ria_da_Civiliza%C3%A7%C3%A3o.jpg',
      genre: 'Civilização ',
      publisher: 'Devir Brasil',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 47,
      name: 'Ticket to Ride',
      year: '2014',
      age: '8+',
      numberOfPlayers: '2 a 5',
      duration: '45',
      description:
        'With elegantly simple gameplay, Ticket to Ride can be learned in under 15 minutes, while providing players with intense strategic and tactical decisions every turn. Players collect cards of various types of train cars they then use to claim railway routes in North America. The longer the routes, the more points they earn. Additional points come to those who fulfill Destination Tickets – goal cards that connect distant cities; and to the player who builds the longest continuous route.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703540/Ticket_to_Ride.png',
      genre: 'Transporte ',
      publisher: 'Galápagos Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 48,
      name: 'Twilight Struggle',
      year: '2016',
      age: '13+',
      numberOfPlayers: '2',
      duration: '180',
      description:
        "In 1945, unlikely allies toppled Hitler's war machine, while humanity's most devastating weapons forced the Japanese Empire to its knees in a storm of fire. Where once there stood many great powers, there then stood only two. The world had scant months to sigh its collective relief before a new conflict threatened. Unlike the titanic struggles of the preceding decades, this conflict would be waged not primarily by soldiers and tanks, but by spies and politicians, scientists and intellectuals, artists and traitors. ",
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703530/Twilight-Struggle-jogo-de-tabuleiro.jpg',
      genre: 'Estratégia ',
      publisher: 'Devir Brasil',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 49,
      name: 'Village',
      year: '2016',
      age: '12+',
      numberOfPlayers: '2 a 4',
      duration: '75',
      description:
        'Life in the village is hard – but life here also allows the inhabitants to grow and prosper as they please. One villager might want to become a friar. Another might feel ambitious and strive for a career in public office. A third one might want to seek his luck in distant lands.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703527/Village.jpg',
      genre: 'Agricultura',
      publisher: 'Fire on Board Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 50,
      name: 'War',
      year: '1972',
      age: '10+',
      numberOfPlayers: '3 a 6',
      duration: '120',
      description:
        'Arguably one of the most popular boardgames in Brazil, War is a modified version of Risk, using concepts that were later introduced in the original game, like objective cards.  The players maneuver armies on a world map, trying to conquer continents, and trying to fulfill their objectives.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703525/War.jpg',
      genre: 'Guerra',
      publisher: 'Grow ',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 51,
      name: 'Zombie Dice',
      year: '2014',
      age: '10+',
      numberOfPlayers: '2 a 99',
      duration: '10',
      description:
        'In Zombie Dice, you are a zombie. You want braaains – more brains than any of your zombie buddies. The 13 custom dice are your victims. Push your luck to eat their brains, but stop rolling before the shotgun blasts end your turn! Whoever collects 13 brains first wins. Each game takes 10 to 20 minutes and can be taught in a single round.',
      coverImage:
        'https://res.cloudinary.com/dt8uln994/image/upload/v1526703531/Zombie_Dice.jpg',
      genre: 'Zumbis',
      publisher: 'Galápagos Jogos',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
    {
      id: 52,
      name: 'Jogo viking',
      year: '1200',
      age: '21+',
      numberOfPlayers: '2',
      duration: '15',
      description: 'ESCANDINAVO',
      coverImage:
        'https://prod-cdn-history-co-uk.s3.amazonaws.com/s3fs-public/styles/medium_square/public/vikingscast_0.jpg?MlsnUa4SqmxLw_ZmSMYPexUGYx.6zPVy',
      genre: 'Estratégia',
      publisher: 'NULL',
      sellingPrice: 0,
      likes: null,
      views: null,
      ownerships: null,
      profile: null,
    },
  ]);
// requestAckbar('api/Games', 'GET');

export const postPlayerSignup = (
  email,
  password,
  avatarUrl,
  collectionSize,
  weeklyPlayTime,
) =>
  requestAckbar('api/Player/Signup', 'POST', {
    email,
    password,
    avatarUrl,
    collectionSize,
    weeklyPlayTime,
  });

export const postViewGame = (gameId, token) =>
  requestAckbar(`api/Player/ViewGame/${gameId}`, 'POST', { token });

export const postLikeGame = (gameId, token) =>
  requestAckbar(`api/Player/LikeGame/${gameId}`, 'POST', { token });

export const postOwnGame = (gameId, token) =>
  requestAckbar(`api/Player/OwnGame/${gameId}`, 'POST', { token });

export const getPlayerInfo = token =>
  requestAckbar(`api/Player/Info`, 'GET', { token });

export const getRecommendations = token =>
  requestAckbar('api/Player/Recommendations', 'GET', { token });

export const postLogin = (email, password) =>
  requestAckbar('api/User/Login', 'POST', { email, password });

export const getCustomerInfo = token =>
  requestAckbar('api/Customer/Info', 'GET', { token });

// deprecated
export const postSignup = (email, password) =>
  requestAckbar('api/User/Signup', 'POST', { email, password });

export default {
  getGameList,
  postPlayerSignup,
  postViewGame,
  postLikeGame,
  postOwnGame,
  getPlayerInfo,
  getRecommendations,
  postLogin,
  getCustomerInfo,
  postSignup,
};
